# Generated by Django 3.0.5 on 2021-11-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Start_Date_time', models.DateTimeField()),
                ('End_Date_time', models.DateTimeField()),
                ('Candidate_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Candidate')),
                ('Interviewer_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Interviewer')),
            ],
        ),
    ]
